services:
  - type: web
    name: tg-ai-autoposter
    env: python
    plan: free
    autoDeploy: true
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: POST_HOUR
        value: "12"
      - key: POST_MINUTE
        value: "0"
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "8080"
